2025-03-13 10:01:05 - INFO - Started server process [2440]
2025-03-13 10:01:05 - INFO - Waiting for application startup.
2025-03-13 10:01:05 - INFO - Application startup complete.
2025-03-13 10:01:05 - INFO - Uvicorn running on https://127.0.0.1:8000 (Press CTRL+C to quit)
2025-03-13 10:01:07 - INFO - root() - ルートにアクセスしました
2025-03-13 10:01:07 - DEBUG - token: None
2025-03-13 10:01:07 - ERROR - 例外ハンドラーが呼ばれました: {'method_name': 'get_max_age()', 'message': 'Cookie情報が取得できませんでした'}
2025-03-13 10:14:40 - INFO - Started server process [7176]
2025-03-13 10:14:40 - INFO - Waiting for application startup.
2025-03-13 10:14:40 - INFO - Application startup complete.
2025-03-13 10:14:40 - INFO - Uvicorn running on https://127.0.0.1:8000 (Press CTRL+C to quit)
2025-03-13 10:15:35 - INFO - root() - ルートにアクセスしました
2025-03-13 10:15:35 - DEBUG - token: None
2025-03-13 10:15:35 - ERROR - 例外ハンドラーが呼ばれました: {'method_name': 'get_max_age()', 'message': 'Cookie情報が取得できませんでした'}
2025-03-13 10:15:36 - INFO - root() - ルートにアクセスしました
2025-03-13 10:15:36 - DEBUG - token: None
2025-03-13 10:15:36 - ERROR - 例外ハンドラーが呼ばれました: {'method_name': 'get_max_age()', 'message': 'Cookie情報が取得できませんでした'}
2025-03-13 10:15:46 - INFO - Started server process [18744]
2025-03-13 10:15:46 - INFO - Waiting for application startup.
2025-03-13 10:15:46 - INFO - Application startup complete.
2025-03-13 10:15:46 - INFO - Uvicorn running on https://127.0.0.1:8000 (Press CTRL+C to quit)
2025-03-13 10:15:48 - INFO - root() - ルートにアクセスしました
2025-03-13 10:15:48 - DEBUG - token: None
2025-03-13 10:15:48 - ERROR - 例外ハンドラーが呼ばれました: {'method_name': 'get_max_age()', 'message': 'Cookie情報が取得できませんでした'}
2025-03-13 10:18:38 - INFO - Started server process [19000]
2025-03-13 10:18:38 - INFO - Waiting for application startup.
2025-03-13 10:18:38 - INFO - Application startup complete.
2025-03-13 10:18:38 - INFO - Uvicorn running on https://127.0.0.1:8000 (Press CTRL+C to quit)
2025-03-13 10:18:40 - INFO - root() - ルートにアクセスしました
2025-03-13 10:18:40 - DEBUG - token: None
2025-03-13 10:18:40 - ERROR - 例外ハンドラーが呼ばれました: {'method_name': 'get_max_age()', 'message': 'Cookie情報が取得できませんでした'}
2025-03-13 10:18:42 - INFO - root() - ルートにアクセスしました
2025-03-13 10:18:42 - DEBUG - token: None
2025-03-13 10:18:42 - ERROR - 例外ハンドラーが呼ばれました: {'method_name': 'get_max_age()', 'message': 'Cookie情報が取得できませんでした'}
2025-03-13 10:19:35 - INFO - Started server process [16972]
2025-03-13 10:19:35 - INFO - Waiting for application startup.
2025-03-13 10:19:35 - INFO - Application startup complete.
2025-03-13 10:19:35 - INFO - Uvicorn running on https://127.0.0.1:8000 (Press CTRL+C to quit)
2025-03-13 10:19:37 - INFO - root() - ルートにアクセスしました
2025-03-13 10:19:37 - DEBUG - token: None
2025-03-13 10:19:37 - ERROR - 例外ハンドラーが呼ばれました: {'method_name': 'get_max_age()', 'message': 'Cookie情報が取得できませんでした'}
2025-03-13 10:20:26 - INFO - Started server process [9196]
2025-03-13 10:20:26 - INFO - Waiting for application startup.
2025-03-13 10:20:26 - INFO - Application startup complete.
2025-03-13 10:20:26 - INFO - Uvicorn running on https://127.0.0.1:8000 (Press CTRL+C to quit)
2025-03-13 10:20:27 - INFO - root() - ルートにアクセスしました
2025-03-13 10:20:27 - DEBUG - token: None
2025-03-13 10:20:27 - ERROR - 例外ハンドラーが呼ばれました: {'method_name': 'get_max_age()', 'message': 'Cookie情報が取得できませんでした'}
2025-03-13 10:21:15 - INFO - Started server process [15828]
2025-03-13 10:21:15 - INFO - Waiting for application startup.
2025-03-13 10:21:15 - INFO - Application startup complete.
2025-03-13 10:21:15 - INFO - Uvicorn running on https://127.0.0.1:8000 (Press CTRL+C to quit)
2025-03-13 10:21:18 - INFO - root() - ルートにアクセスしました
2025-03-13 10:21:18 - DEBUG - token: None
2025-03-13 10:21:18 - DEBUG - token: ありません
2025-03-13 10:22:17 - INFO - 認証試行: user1
2025-03-13 10:22:17 - INFO - 認証成功: user1
2025-03-13 10:22:17 - DEBUG - redirect_url: /order_complete
2025-03-13 10:22:17 - DEBUG - login_post() - 'sub': user1
2025-03-13 10:22:17 - DEBUG - login_post() - 'token': eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMSIsInBlcm1pc3Npb24iOjEsIm1heC1hZ2UiOiIyMDI1LTA0LTEyVDAxOjIyOjE3LjYxNTk3MloifQ.aa2xsDdM7DZUeRSL8EU9DVhKkb7wqAXZouF2Rbtrf0I
2025-03-13 10:22:17 - DEBUG - login_post() - 'exp': 2025-04-12T01:22:17.615972Z
2025-03-13 10:22:17 - DEBUG - login_post() - 'permission': 1
2025-03-13 10:22:17 - ERROR - 例外ハンドラーが呼ばれました: {'method_name': 'regist_complete()', 'message': "予期せぬエラーが発生しました: 'NoneType' object is not subscriptable"}
2025-03-13 10:25:29 - INFO - Started server process [19288]
2025-03-13 10:25:29 - INFO - Waiting for application startup.
2025-03-13 10:25:29 - INFO - Application startup complete.
2025-03-13 10:25:29 - INFO - Uvicorn running on https://127.0.0.1:8000 (Press CTRL+C to quit)
2025-03-13 10:25:30 - INFO - root() - ルートにアクセスしました
2025-03-13 10:25:30 - DEBUG - token: None
2025-03-13 10:25:30 - DEBUG - token: ありません
2025-03-13 10:25:50 - INFO - 認証試行: user1
2025-03-13 10:25:50 - INFO - 認証成功: user1
2025-03-13 10:25:50 - DEBUG - redirect_url: /order_complete
2025-03-13 10:25:50 - DEBUG - login_post() - 'sub': user1
2025-03-13 10:25:50 - DEBUG - login_post() - 'token': eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMSIsInBlcm1pc3Npb24iOjEsIm1heC1hZ2UiOiIyMDI1LTA0LTEyVDAxOjI1OjUwLjYzMzEyN1oifQ.GjPpd2UN6by8EyLn4Ha9Pdx6Jo0xdzuoZC1NrCAt9Xw
2025-03-13 10:25:50 - DEBUG - login_post() - 'max-age': 2025-04-12T01:25:50.633127Z
2025-03-13 10:25:50 - DEBUG - login_post() - 'permission': 1
2025-03-13 10:25:50 - DEBUG - orders: [Order(order_id=1, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 7, 10, 20), canceled=False), Order(order_id=7, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 7, 10, 27), canceled=False), Order(order_id=8, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 7, 10, 31), canceled=False), Order(order_id=9, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 7, 12, 1), canceled=False), Order(order_id=10, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 7, 13, 34), canceled=False), Order(order_id=11, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 7, 14, 7), canceled=False), Order(order_id=12, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 7, 14, 9), canceled=False), Order(order_id=13, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 7, 14, 14), canceled=False), Order(order_id=14, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 7, 14, 21), canceled=False), Order(order_id=15, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 7, 14, 25), canceled=False), Order(order_id=16, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 7, 14, 46), canceled=False), Order(order_id=17, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 7, 15, 27), canceled=False), Order(order_id=18, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 10, 11, 57), canceled=False), Order(order_id=19, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 10, 14, 23), canceled=False), Order(order_id=20, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 10, 14, 29), canceled=True), Order(order_id=21, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 10, 14, 30), canceled=False), Order(order_id=22, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 10, 15, 16), canceled=False), Order(order_id=23, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 10, 15, 27), canceled=False), Order(order_id=24, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 12, 10, 41), canceled=False), Order(order_id=25, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 12, 13, 15), canceled=False), Order(order_id=26, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 13, 10, 25), canceled=False)]
2025-03-13 10:25:52 - INFO - root() - ルートにアクセスしました
2025-03-13 10:25:52 - INFO - stop_twice_order() - きょう２度目の注文を阻止
2025-03-13 10:25:54 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "C:\Obento-Test\v_0.1.6\app\utils\utils.py", line 184, in delete_all_cookies
    response.delete_cookie(key="max-age")
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\responses.py", line 135, in delete_cookie
    self.set_cookie(
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\responses.py", line 100, in set_cookie
    cookie[key] = value
    ~~~~~~^^^^^
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\http\cookies.py", line 480, in __setitem__
    self.__set(key, rval, cval)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\http\cookies.py", line 470, in __set
    M.set(key, real_value, coded_value)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\http\cookies.py", line 333, in set
    raise CookieError('Attempt to set a reserved key %r' % (key,))
http.cookies.CookieError: Attempt to set a reserved key 'max-age'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Obento-Test\v_0.1.6\app\utils\utils.py", line 23, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Obento-Test\v_0.1.6\app\main.py", line 350, in clear_cookie
    delete_all_cookies(response)
  File "C:\Obento-Test\v_0.1.6\app\utils\utils.py", line 32, in sync_wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Obento-Test\v_0.1.6\app\utils\utils.py", line 192, in delete_all_cookies
    raise CookieException(
          ^^^^^^^^^^^^^^^^
TypeError: CookieException.__init__() got an unexpected keyword argument 'message'
2025-03-13 10:26:09 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "C:\Obento-Test\v_0.1.6\app\utils\utils.py", line 184, in delete_all_cookies
    response.delete_cookie(key="max-age")
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\responses.py", line 135, in delete_cookie
    self.set_cookie(
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\responses.py", line 100, in set_cookie
    cookie[key] = value
    ~~~~~~^^^^^
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\http\cookies.py", line 480, in __setitem__
    self.__set(key, rval, cval)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\http\cookies.py", line 470, in __set
    M.set(key, real_value, coded_value)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\http\cookies.py", line 333, in set
    raise CookieError('Attempt to set a reserved key %r' % (key,))
http.cookies.CookieError: Attempt to set a reserved key 'max-age'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Obento-Test\v_0.1.6\app\utils\utils.py", line 23, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Obento-Test\v_0.1.6\app\main.py", line 350, in clear_cookie
    delete_all_cookies(response)
  File "C:\Obento-Test\v_0.1.6\app\utils\utils.py", line 32, in sync_wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Obento-Test\v_0.1.6\app\utils\utils.py", line 192, in delete_all_cookies
    raise CookieException(
          ^^^^^^^^^^^^^^^^
TypeError: CookieException.__init__() got an unexpected keyword argument 'message'
2025-03-13 10:27:33 - INFO - Started server process [15420]
2025-03-13 10:27:33 - INFO - Waiting for application startup.
2025-03-13 10:27:33 - INFO - Application startup complete.
2025-03-13 10:27:33 - INFO - Uvicorn running on https://127.0.0.1:8000 (Press CTRL+C to quit)
2025-03-13 10:27:34 - INFO - root() - ルートにアクセスしました
2025-03-13 10:27:34 - INFO - stop_twice_order() - きょう２度目の注文を阻止
2025-03-13 10:27:35 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "C:\Obento-Test\v_0.1.6\app\utils\utils.py", line 184, in delete_all_cookies
    response.delete_cookie(key="max-age")
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\responses.py", line 135, in delete_cookie
    self.set_cookie(
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\responses.py", line 100, in set_cookie
    cookie[key] = value
    ~~~~~~^^^^^
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\http\cookies.py", line 480, in __setitem__
    self.__set(key, rval, cval)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\http\cookies.py", line 470, in __set
    M.set(key, real_value, coded_value)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\http\cookies.py", line 333, in set
    raise CookieError('Attempt to set a reserved key %r' % (key,))
http.cookies.CookieError: Attempt to set a reserved key 'max-age'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensy\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Obento-Test\v_0.1.6\app\utils\utils.py", line 23, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Obento-Test\v_0.1.6\app\main.py", line 350, in clear_cookie
    delete_all_cookies(response)
  File "C:\Obento-Test\v_0.1.6\app\utils\utils.py", line 32, in sync_wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Obento-Test\v_0.1.6\app\utils\utils.py", line 192, in delete_all_cookies
    raise CookieException(
          ^^^^^^^^^^^^^^^^
TypeError: CookieException.__init__() got an unexpected keyword argument 'message'
2025-03-13 10:31:36 - INFO - Started server process [4924]
2025-03-13 10:31:36 - INFO - Waiting for application startup.
2025-03-13 10:31:36 - INFO - Application startup complete.
2025-03-13 10:31:36 - INFO - Uvicorn running on https://127.0.0.1:8000 (Press CTRL+C to quit)
2025-03-13 10:31:38 - INFO - root() - ルートにアクセスしました
2025-03-13 10:31:38 - INFO - stop_twice_order() - きょう２度目の注文を阻止
2025-03-13 10:31:40 - ERROR - 例外ハンドラーが呼ばれました: {'method_name': 'delete_all_cookies()', 'message': "Attempt to set a reserved key 'max-age'"}
2025-03-13 10:34:08 - INFO - Started server process [14312]
2025-03-13 10:34:08 - INFO - Waiting for application startup.
2025-03-13 10:34:09 - INFO - Application startup complete.
2025-03-13 10:34:09 - INFO - Uvicorn running on https://127.0.0.1:8000 (Press CTRL+C to quit)
2025-03-13 10:34:10 - INFO - root() - ルートにアクセスしました
2025-03-13 10:34:10 - INFO - stop_twice_order() - きょう２度目の注文を阻止
2025-03-13 10:34:12 - INFO - root() - ルートにアクセスしました
2025-03-13 10:34:12 - DEBUG - token: None
2025-03-13 10:34:12 - DEBUG - token: ありません
2025-03-13 10:34:18 - INFO - 認証試行: user1
2025-03-13 10:34:18 - INFO - 認証成功: user1
2025-03-13 10:34:18 - DEBUG - redirect_url: /order_complete
2025-03-13 10:34:18 - DEBUG - login_post() - 'sub': user1
2025-03-13 10:34:18 - DEBUG - login_post() - 'token': eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMSIsInBlcm1pc3Npb24iOjEsIm1heC1hZ2UiOiIyMDI1LTA0LTEyVDAxOjM0OjE4LjYzNjc5NFoifQ.q-mtiRC3tzGQLeNh5cLE0GykNsfF9ExgDvOLQcEq5mE
2025-03-13 10:34:18 - DEBUG - login_post() - 'max-age': 2025-04-12T01:34:18.636794Z
2025-03-13 10:34:18 - DEBUG - login_post() - 'permission': 1
2025-03-13 10:34:18 - DEBUG - orders: [Order(order_id=1, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 7, 10, 20), canceled=False), Order(order_id=7, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 7, 10, 27), canceled=False), Order(order_id=8, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 7, 10, 31), canceled=False), Order(order_id=9, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 7, 12, 1), canceled=False), Order(order_id=10, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 7, 13, 34), canceled=False), Order(order_id=11, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 7, 14, 7), canceled=False), Order(order_id=12, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 7, 14, 9), canceled=False), Order(order_id=13, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 7, 14, 14), canceled=False), Order(order_id=14, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 7, 14, 21), canceled=False), Order(order_id=15, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 7, 14, 25), canceled=False), Order(order_id=16, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 7, 14, 46), canceled=False), Order(order_id=17, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 7, 15, 27), canceled=False), Order(order_id=18, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 10, 11, 57), canceled=False), Order(order_id=19, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 10, 14, 23), canceled=False), Order(order_id=20, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 10, 14, 29), canceled=True), Order(order_id=21, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 10, 14, 30), canceled=False), Order(order_id=22, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 10, 15, 16), canceled=False), Order(order_id=23, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 10, 15, 27), canceled=False), Order(order_id=24, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 12, 10, 41), canceled=False), Order(order_id=25, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 12, 13, 15), canceled=False), Order(order_id=26, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 13, 10, 25), canceled=False), Order(order_id=27, company_name='テンシステム', username='user1', shop_name='shop01', menu_name='お昼の定食', amount=1, created_at=datetime.datetime(2025, 3, 13, 10, 34), canceled=False)]
2025-03-13 10:34:21 - INFO - root() - ルートにアクセスしました
2025-03-13 10:34:21 - INFO - stop_twice_order() - きょう２度目の注文を阻止
2025-03-13 10:34:22 - INFO - root() - ルートにアクセスしました
2025-03-13 10:34:22 - DEBUG - token: None
2025-03-13 10:34:22 - DEBUG - token: ありません
